services:
  - type: web_service
    name: volt-hosting
    runtime: python
    plan: free
    repo: https://github.com/Volt089/volt-hosting
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python voltxx.py
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        value: "8992507650:AAESaPijyyAJxEgqX4_hcDRzQGkxp1lhStE"
      - key: OWNER_IDS
        value: "8747221712"
      - key: CO_OWNER_IDS
        value: "5769074791"
      - key: TIDB_HOST
        value: "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
      - key: TIDB_PORT
        value: "4000"
      - key: TIDB_USER
        value: "4VMCiZGCddWQNae.root"
      - key: TIDB_PASSWORD
        value: "we07UuqhfChTVUqt"
      - key: TIDB_DATABASE
        value: "volt_hosting"
      - key: DB_SSL
        value: "1"